// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Project': typeof import('../components/project.vue')['default'],
    'Skills': typeof import('../components/skills.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
